---
services:
  - docker

cache:
  directories:
  - /tmp/m2

before_install:
  - docker build -t kstreams .

script:
  - docker run -v /tmp/m2:/root/.m2 -v $TRAVIS_BUILD_DIR:/data --rm kstreams /bin/bash -c "mvn verify"

after_success:
  - cd slides/target/generated-slides
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
